import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b px-6 py-4 flex justify-between items-center">
          <Link href="/" className="text-xl font-bold">
            RapidFire SFT
          </Link>
          <nav className="flex space-x-2">
            <Link href="/" className="px-4 py-2 rounded-md border border-transparent hover:border-neutral-300 hover:bg-neutral-50 transition-colors font-semibold">Home</Link>
            <Link href="/experiments" className="px-4 py-2 rounded-md border border-transparent hover:border-neutral-300 hover:bg-neutral-50 transition-colors font-semibold">Experiments</Link>
            <Link href="/results" className="px-4 py-2 rounded-md border border-transparent hover:border-neutral-300 hover:bg-neutral-50 transition-colors font-semibold">Results</Link>
            <Link href="/reproducibility" className="px-4 py-2 rounded-md border border-transparent hover:border-neutral-300 hover:bg-neutral-50 transition-colors font-semibold">Reproducibility</Link>
            <Link href="/repo" className="px-4 py-2 rounded-md border border-transparent hover:border-neutral-300 hover:bg-neutral-50 transition-colors font-semibold">Repo</Link>
          </nav>
        </header>
        {children}
        <footer className="border-t mt-16 py-6 text-center text-sm text-neutral-500">
          <div>RapidFire SFT Experiments</div>
          <div className="mt-1">UC San Diego — ML Experiment Study</div>
          <div className="mt-1">
            Built using RapidFire AI, HuggingFace Transformers, and Next.js.
          </div>
        </footer>
      </body>
    </html>
  );
}
