project:
  type: website
  output-dir: _site

website:
  navbar: false
  sidebar:
    style: "floating"
  page-navigation: true

format:
  html:
    css: assets/styles.css
    code-fold: false
    code-tools: true
    code-copy: true
    fig-responsive: true
    link-external-newwindow: true
    toc: true
    toc-location: right